package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"math/rand/v2"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"time"

	"github.com/gorilla/websocket"
	_ "github.com/lib/pq"
	"github.com/redis/go-redis/v9"
)

// UIPlayer represents the unified leaderboard row data structure
type UIPlayer struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Score    float64 `json:"score"`
	Rank     int     `json:"rank"`
}

// WSMessage serves as the generic envelope wrapper for all stream variants
type WSMessage struct {
	Type string      `json:"type"`
	Data interface{} `json:"data"`
}

// Activity tracks real-time micro-events generated by ingestion streams
type Activity struct {
	Username string `json:"username"`
	Gain     int64  `json:"gain"`
	Time     string `json:"time"`
}

var (
	activeClients = make(map[*websocket.Conn]bool)
	clientsMu     sync.RWMutex
	upgrader      = websocket.Upgrader{
		ReadBufferSize:  1024,
		WriteBufferSize: 1024,
		CheckOrigin:     func(r *http.Request) bool { return true },
	}
	usernameCache = map[string]string{
		"user_01": "Alice_BTC",
		"user_02": "Bob_ETH",
		"user_03": "Charlie_SOL",
		"user_04": "David_XRP",
		"user_05": "Emma_DOGE",
		"user_06": "Frank_BNB",
		"user_07": "Grace_AVAX",
		"user_08": "Henry_LINK",
		"user_09": "Ivy_ADA",
		"user_10": "Jack_DOT",
	}
)

func main() {
	ctx := context.Background()

	pgConnStr := "host=localhost port=5432 user=postgres password=local_password dbname=postgres sslmode=disable"
	db, err := sql.Open("postgres", pgConnStr)
	if err != nil {
		log.Fatalf("Failed to initialize Postgres driver connection: %v", err)
	}

	rdb := redis.NewClient(&redis.Options{Addr: "localhost:6379"})

	if err := createTableIfNotExists(db); err != nil {
		log.Fatalf("Failed to create postgres tables: %v", err)
	}
	fmt.Println("Databases connected and schema ready.")

	// HTTP API Endpoint (Keeps flat array representation for direct pull data compatibility)
	http.HandleFunc("/api/leaderboard", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Content-Type", "application/json")

		topPlayers, err := GetTopPlayers(ctx, rdb, 10)
		if err != nil {
			http.Error(w, "Failed to fetch leaderboard", http.StatusInternalServerError)
			return
		}

		var payload []UIPlayer
		for idx, p := range topPlayers {
			userID := fmt.Sprintf("%v", p.Member)
			payload = append(payload, UIPlayer{
				ID:       userID,
				Username: usernameCache[userID],
				Score:    p.Score,
				Rank:     idx + 1,
			})
		}
		json.NewEncoder(w).Encode(payload)
	})

	http.HandleFunc("/ws/leaderboard", HandleLeaderboardWS)

	players := []struct {
		id    string
		name  string
		score int64
	}{
		{"user_01", "Alice_BTC", 1200},
		{"user_02", "Bob_ETH", 980},
		{"user_03", "Charlie_SOL", 870},
		{"user_04", "David_XRP", 790},
		{"user_05", "Emma_DOGE", 720},
		{"user_06", "Frank_BNB", 680},
		{"user_07", "Grace_AVAX", 610},
		{"user_08", "Henry_LINK", 540},
		{"user_09", "Ivy_ADA", 470},
		{"user_10", "Jack_DOT", 410},
	}

	fmt.Println("Initializing leaderboard...")
	for _, p := range players {
		if err := updatePlayerScore(ctx, db, rdb, p.id, p.name, p.score); err != nil {
			log.Printf("Failed to initialize %s: %v", p.name, err)
		}
	}

	// Background Simulator Running Pipeline
	go func() {
		ticker := time.NewTicker(3 * time.Second)
		defer ticker.Stop()

		for range ticker.C {
			targetPlayer := players[rand.IntN(len(players))]
			scoreGain := int64(50)

			err := updatePlayerScore(ctx, db, rdb, targetPlayer.id, targetPlayer.name, scoreGain)
			if err != nil {
				log.Printf("[ERROR] Ingestion write failure: %v", err)
				continue
			}

			log.Printf("[Simulator] Added %d points to %s", scoreGain, targetPlayer.name)
			
			// Broadcast split message sequence sequentially
			BroadcastLeaderboardUpdate(ctx, rdb)
			BroadcastActivity(targetPlayer.name, scoreGain)
		}
	}()

	shutdownChan := make(chan os.Signal, 1)
	signal.Notify(shutdownChan, os.Interrupt)

	go func() {
		log.Println("Backend Server running live on http://localhost:8080")
		if err := http.ListenAndServe(":8080", nil); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server shutdown unexpectedly: %v", err)
		}
	}()

	<-shutdownChan
	fmt.Println("\nShutdown signal detected! Starting graceful drainage sequence...")

	clientsMu.Lock()
	for clientConn := range activeClients {
		_ = clientConn.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, "Server shutting down"))
		clientConn.Close()
	}
	clientsMu.Unlock()

	db.Close()
	rdb.Close()
	fmt.Println("Graceful shutdown sequence finished.")
}

func HandleLeaderboardWS(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("Failed to upgrade socket connection: %v", err)
		return
	}

	clientsMu.Lock()
	activeClients[conn] = true
	clientsMu.Unlock()

	log.Printf("New client connected.")

	go func() {
		defer func() {
			conn.Close()
			clientsMu.Lock()
			delete(activeClients, conn)
			clientsMu.Unlock()
		}()
		for {
			if _, _, err := conn.ReadMessage(); err != nil {
				break
			}
		}
	}()
}

func BroadcastLeaderboardUpdate(ctx context.Context, rdb *redis.Client) {
	topPlayers, err := GetTopPlayers(ctx, rdb, 10)
	if err != nil {
		return
	}

	var dataset []UIPlayer
	for idx, p := range topPlayers {
		userID := fmt.Sprintf("%v", p.Member)
		dataset = append(dataset, UIPlayer{
			ID:       userID,
			Username: usernameCache[userID],
			Score:    p.Score,
			Rank:     idx + 1,
		})
	}

	// Encapsulate structured state snapshot 
	wrapper := WSMessage{
		Type: "leaderboard",
		Data: dataset,
	}

    
    jsonBytes, err := json.Marshal(wrapper)
    if err != nil {
        return
    }

    log.Println("=== LEADERBOARD MESSAGE ===")
    log.Println(string(jsonBytes))

	clientsMu.RLock()
	defer clientsMu.RUnlock()
	for clientConn := range activeClients {
		err := clientConn.WriteMessage(websocket.TextMessage, jsonBytes)
		if err != nil {
			clientConn.Close()
		}
	}
}

func BroadcastActivity(username string, gain int64) {
	activity := Activity{
		Username: username,
		Gain:     gain,
		Time:     "Just now",
	}

	message := WSMessage{
		Type: "activity",
		Data: activity,
	}

	jsonBytes, err := json.Marshal(message)
	if err != nil {
		return
	}

	clientsMu.RLock()
	defer clientsMu.RUnlock()

	for clientConn := range activeClients {
		err := clientConn.WriteMessage(
			websocket.TextMessage,
			jsonBytes,
		)

		if err != nil {
			clientConn.Close()
		}
	}

    
}

func createTableIfNotExists(db *sql.DB) error {
	query := `
    CREATE TABLE IF NOT EXISTS users (
        user_id VARCHAR(50) PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        score BIGINT DEFAULT 0 NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );`
	_, err := db.Exec(query)
	return err
}

func updatePlayerScore(ctx context.Context, db *sql.DB, rdb *redis.Client, userID string, username string, scoreDelta int64) error {
	pgQuery := `
        INSERT INTO users (user_id, username, score, updated_at)
        VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
        ON CONFLICT (user_id) 
        DO UPDATE SET score = users.score + EXCLUDED.score, updated_at = CURRENT_TIMESTAMP;
    `
	_, err := db.Exec(pgQuery, userID, username, scoreDelta)
	if err != nil {
		return fmt.Errorf("postgres fail: %w", err)
	}
	return rdb.ZIncrBy(ctx, "leaderboard:crypto", float64(scoreDelta), userID).Err()
}

func GetTopPlayers(ctx context.Context, rdb *redis.Client, n int64) ([]redis.Z, error) {
	return rdb.ZRevRangeWithScores(ctx, "leaderboard:crypto", 0, n-1).Result()
}